# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
    - releases/*

resources:
- repo: self

pool:
  name: Self-Hosted Cloud Dev-Test .NET
  demands:
  - msbuild
  - visualstudio
  - vstest

variables:
  buildConfiguration: 'Release'
  ngBuildConfiguration: 'qa'

steps:
- task: Npm@1
  inputs:
    command: 'install'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build --qa'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/dist/CargoApp.zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: CargoApps
    targetPath: '$(Build.ArtifactStagingDirectory)/dist/CargoApp.zip'